### ISSUE TITLE
fakes3 gem is locked to 0.2.4

### ISSUE THREAD

**Issue by bramus** [instructure/dockerfiles#2]
I've noticed that fakes3 gem used in the [fake-3s appliance](https://github.com/instructure/dockerfiles/tree/master/appliances/fake-s3) has [newer releases](https://rubygems.org/gems/fakes3/versions/) _(viz. 0.2.5 and 1.0.0)_ than the version contained in the docker image.

Is there a specific reason why the fake-3s appliance has it [locked down to 0.2.4](https://github.com/instructure/dockerfiles/commit/e0cea6f44a702106e93dcb307113e922d811a046#diff-3471373c9dcf173839ae824795c6e137R15), or may it be updated to the latest version?

Regards,
B!

**Comment by FreedomBen** [comment]
Hi @bramus .  Most likely nobody has gotten around to updating and testing it since we only use it in development.  I'll ping internally and see.

**Comment by bramus** [comment]
Read the note about 1.0.0 in the PR. Good call. Thanks.
